import { defineConfig } from 'vite-plus'

export default defineConfig({
  fmt: {
    ignorePatterns: [
      '.agents/**',
      '*.md',
      'pages/**',
      'registry/**',
      '**/permissions/**',
      '**/worker-configuration.d.ts',
    ],
    endOfLine: 'lf',
    semi: false,
    useTabs: false,
    printWidth: 100,
    tabWidth: 2,
    singleQuote: true,
    sortPackageJson: { sortScripts: true },
    arrowParens: 'avoid',
    jsxSingleQuote: true,
    singleAttributePerLine: false,
    bracketSameLine: false,
    bracketSpacing: true,
    embeddedLanguageFormatting: 'auto',
    insertFinalNewline: false,
    proseWrap: 'always',
    htmlWhitespaceSensitivity: 'css',
    objectWrap: 'collapse',
    quoteProps: 'consistent',
    trailingComma: 'all',
  },
  lint: {
    categories: { correctness: 'error' },
    ignorePatterns: ['.agents/**', '.vscode/**', '*.md'],
    options: { typeAware: true, typeCheck: true },
    rules: { 'no-thenable': 'allow' },
  },
  test: { include: ['test-vite/**/*.vitest.ts'] },
})