name: 删除插件
description: 向注册表中添加或更新插件
title: '[删除插件] <名称>'
labels:
  - RemovePlugin
assignees:
  - delta-comic-bot
body:
  - type: markdown
    attributes:
      value: |
        提交时请将上方标题中 `<>` 占位符替换为实际名称。

  - type: input
    id: id
    attributes:
      label: 名称
      description: 你插件的ID
    validations:
      required: true