name: 添加/更新插件
description: 向注册表中添加或更新插件
title: '[添加/更新插件] <名称>'
labels:
  - UpsertPlugin
assignees:
  - delta-comic-bot
body:
  - type: markdown
    attributes:
      value: |
        提交时请将上方标题中 `<>` 占位符替换为实际名称。

  - type: input
    id: id
    attributes:
      label: 名称
      description: 你插件的ID
    validations:
      required: true

  - type: input
    id: download
    attributes:
      label: 下载方式
      description: 输入下载语句, 自动重定向
      placeholder: gh:delta-comic/delta-comic-plugin-bika
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 作者
      description: (选填)填入其他的，用`,`分割的作者。注意："你"默认是作者
      placeholder: 'wenxig, li-lei, han-meimei'